### ISSUE TITLE
Problem with transition preselection with two nuclei

### ISSUE THREAD

**Issue by cetait** [StollLab/EasySpin#241]
Using pepper with `Opt.Method = 'matrix'` and one strongly and one weakly coupled nucleus leads to a spectrum with artifacts, `Opt.Method = 'perturb'` gives the correct result (see example code below). Setting `Opt.Threshold = 0` fixes the problem.

```
clear; clc; clf;

Exp.mwFreq = 9.65; % GHz
Exp.Range = [340.5 348]; % mT
Exp.Harmonic = 0;

Sys.S = 1/2;
Sys.g = gfree;%[2.0043 2.0037 2.0021];

Sys.Nucs = '14N';
Apar = 50;
Aperp = 15;
Sys.A = [Aperp Aperp Apar]; % MHz

Sys.lwpp = 0.1; % mT

Opt.Method = 'matrix';
Opt.Threshold = 1e-12;

[B,spc1nuc] = pepper(Sys,Exp,Opt);

% Add weakly coupled proton
Sys = nucspinadd(Sys,'1H',[1 1 1]*0.1);
[B,spc2nuc] = pepper(Sys,Exp,Opt);

Opt.Method = 'perturb1';
[B,spc2nucperturb] = pepper(Sys,Exp,Opt);


% Plot
plot(B,spc1nuc,B,spc2nuc,B,spc2nucperturb)
legend('14N matrix','14N,1H matrix','14N,1H perturb1')
xlabel('B (mT)')
```

**Comment by stestoll** [comment]
Currently, transition pre-selection in `resfields` uses only a gridsize of 3. It looks like this is not enough in this multinuclear case with one nucleus with a signficant hyperfine anisotropy. It works fine with just the one nucleus with large hyperfine anisotropy. Why it takes a second nucleus to create this issue is unclear.

Changing the pre-selection gridsize to 4 fixes the problem. Interestingly, `endorfrq` already uses gridsize 4.
