### ISSUE TITLE
Add migration guide from v5 to v6

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#296]

**Comment by stestoll** [comment]
implemented

**Comment by sikuenstner** [comment]
I suggest to provide a final non-expirable release of version 5.2 by removing the function _eschecker_ from the simulation functions.
Many scripts have been written with the ES 5.2 syntax, which will likely break by using ES 6. While I think it is OK to "force" people to use improved analysis tools for new data, I think providing a fallback for published data is required. Otherwise, it is not possible to easily reproduce the analyses performed previously.

**Comment by stestoll** [comment]
EasySpin versions expire to protect users from bugs in old versions that are fixed in newer versions. This is particularly true for the big step from 5.2 to 6.0 - there are many bugs that were fixed in 6.0.

However, users of 5.2 can removes the expiry date with a simple modification: Just replace the `eschecker` function in the `private` folder with the following function:
```matlab
function err = eschecker(varargin);
err = '';
end
```

**Comment by sikuenstner** [comment]
I think that's a good solution.
